apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: devops-training
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/phonevilai/devlop-go-example:8d45efe51ba2ed1f82f4fc0b9117fba4eb10938a
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
